const pieces=[
 ['BELENTANI / OMEGA','belentani7.github.io/index.html','ORIGEN / PORTADA'],['ECOSISTEMA','Belentani/ecosistema.html','MAPA / UNIVERSO'],['JUDAS / GALACTIC','judas-experience-galactic/index.html','EXPERIENCIA / VISUAL'],['JUDAS / STATIC','judas-omega-static/index.html','STORYBOARD / ARCHIVO'],['THE JUDAS EXPERIENCE','the-judas-experience/web/index.html','MÚSICA / INTERFAZ'],['OMEGA IMMERSIVE','belentani_Omega/magic/immersive.html','MAGIC / INMERSIVO'],['SHADER / SIGNAL','Belentani/magic/shader.html','MAGIC / VISUAL'],['SFX / LAB','Belentani/magic/sfx.html','MAGIC / SONIDO'],['DUCK MUSIC LAB','duck-music-lab/index.html','LAB / AUDIO'],['DUCK OMEGA','Duck-Omega/index.html','DUCK / PORTAL'],['DUCK HTML','DuckHTML/index.html','EXPERIMENTO / HTML'],['HEYDUCK','heyduck/index.html','HUB / ECOSISTEMA'],['JUDAS CMS','belentani-the-judas-experience/app/templates/judas.html','CMS / ARCHIVO'],['DUCK INTEGRADO','belentani-the-judas-experience-archive/drive-materials/DUCK-INTEGRADO.html','ARCHIVE / INTEGRADO']
];
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
let index=Math.floor(Date.now()/86400000)%pieces.length; let live=false, timer;
function card(p,i){return `<a class="card" href="archive/${p[1]}" target="_blank" rel="noopener"><span class="num">${String(i+1).padStart(2,'0')}</span><span class="arrow">↗</span><div><h3>${esc(p[0])}</h3><small>${esc(p[2])}</small></div></a>`}
function render(){const p=pieces[index];document.querySelector('#count').textContent=String(pieces.length).padStart(2,'0');document.querySelector('#featured').innerHTML=`<article class="feature-card"><div class="feature-visual" style="--seed:${index}"></div><div class="feature-info"><div class="eyebrow">VERSIÓN ${String(index+1).padStart(2,'0')} / SELECCIONADA AHORA</div><h2>${esc(p[0])}</h2><p>${esc(p[2])}. Una puerta preservada dentro del archivo vivo. La pieza original permanece intacta y se abre en una nueva pestaña.</p><a href="archive/${p[1]}" target="_blank" rel="noopener">ABRIR PIEZA ORIGINAL ↗</a></div></article>`;document.querySelector('#grid').innerHTML=pieces.map(card).join('')}
function next(){index=(index+1)%pieces.length;render()}
document.querySelector('#shuffle').onclick=()=>{index=Math.floor(Math.random()*pieces.length);render();document.querySelector('#featured').scrollIntoView({behavior:'smooth',block:'center'})};
document.querySelector('#auto').onclick=()=>{live=!live;document.querySelector('.dot').classList.toggle('live',live);document.querySelector('#rotation').textContent=live?'ROTACIÓN ACTIVA / 12S':'ROTACIÓN PAUSADA';clearInterval(timer);if(live)timer=setInterval(next,12000)};render();
